# spring.application.name=accounts
# spring.datasource.url = urlName
# spring.datasource.username = username

spring:
  application:
    name: accounts

  datasource:
    url: jdbc:h2:mem:accounts
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true # Enable the H2 console
      path: /h2-console # Optional: Customize the console path

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect # For Hibernate integration
    hibernate:
      ddl-auto: update # Or create-drop, none, validate
      show-sql: true